# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options


class TestSmokeTest():

    def setup_method(self, method):
        options = Options()
        options.add_argument("--headless=new")
        options.add_argument("--no-sandbox")
        options.add_argument("--disable-dev-shm-usage")
        self.driver = webdriver.Chrome(options=options)
        self.wait = WebDriverWait(self.driver, 10)

    def teardown_method(self, method):
        self.driver.quit()

    def test_joinPage(self):
        self.driver.get("https://andreyblanco.github.io/cse270-teton/join.html")
        self.driver.set_window_size(740, 800)

        self.wait.until(EC.presence_of_element_located((By.NAME, "fname")))

        self.driver.find_element(By.NAME, "fname").send_keys("Andrey")
        self.driver.find_element(By.NAME, "lname").send_keys("Blanco")
        self.driver.find_element(By.NAME, "bizname").send_keys("All Media")
        self.driver.find_element(By.NAME, "biztitle").send_keys("Designer")
        self.driver.find_element(By.NAME, "submit").click()

        assert len(self.driver.find_elements(By.NAME, "email")) > 0
        assert len(self.driver.find_elements(By.NAME, "fname")) > 0

    def test_homePage(self):
        self.driver.get("https://andreyblanco.github.io/cse270-teton/index.html")
        self.driver.set_window_size(740, 800)

        self.wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, ".header-logo img")))

        assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").is_displayed()
        assert self.driver.title == "Teton Idaho CoC"
        assert self.driver.find_element(By.CSS_SELECTOR, ".spotlight1").is_displayed()
        assert self.driver.find_element(By.CSS_SELECTOR, ".spotlight2").is_displayed()
        assert self.driver.find_element(By.LINK_TEXT, "Join Us!").is_displayed()

    def test_directoryPage(self):
        self.driver.get("https://andreyblanco.github.io/cse270-teton/directory.html")
        self.driver.set_window_size(740, 800)

        self.driver.find_element(By.ID, "directory-grid").click()

        # ✅ Esperar a que el elemento dinámico aparezca
        element = self.wait.until(
            EC.visibility_of_element_located(
                (By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)")
            )
        )

        assert element.text == "Teton Turf and Tree"

        self.driver.find_element(By.ID, "directory-list").click()

        element = self.wait.until(
            EC.visibility_of_element_located(
                (By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)")
            )
        )

        assert element.text == "Teton Turf and Tree"

    def test_adminPage(self):
        self.driver.get("https://andreyblanco.github.io/cse270-teton/admin.html")
        self.driver.set_window_size(740, 800)

        self.wait.until(EC.presence_of_element_located((By.ID, "username")))

        self.driver.find_element(By.ID, "username").send_keys("Andrey")
        self.driver.find_element(By.ID, "password").send_keys("Blanco")
        self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()

        # ✅ Esperar a que aparezca el texto del error
        self.wait.until(
            EC.text_to_be_present_in_element(
                (By.CSS_SELECTOR, ".errorMessage"),
                "Invalid username and password."
            )
        )

        text = self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").text
        assert text == "Invalid username and password."